# permissions for end users to view alerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alert-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: alert-viewer-role
rules:
- apiGroups:
  - alerting.kotification.io
  resources:
  - alerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerting.kotification.io
  resources:
  - alerts/status
  verbs:
  - get
